"use strict";
if(!SocialNet.requireLogin())throw new Error("Non connecté");
const root=document.getElementById("messengerRoot"),pl=document.getElementById("peopleList"),sl=document.getElementById("searchPeople"),ml=document.getElementById("messagesList"),head=document.getElementById("chatHead"),form=document.getElementById("messageForm"),input=document.getElementById("messageInput"),openGroupBtn=document.getElementById("openGroupBtn"),modal=document.getElementById("groupModal"),closeGroupBtn=document.getElementById("closeGroupBtn"),groupForm=document.getElementById("groupForm"),groupName=document.getElementById("groupName"),groupFriends=document.getElementById("groupFriends"),groupError=document.getElementById("groupError");
let people=[],groups=[],selected=null,activeTab="all",pollTimer=null,lastRendered="";
const me=()=>SocialNet.user();
function personHTML(u){const active=selected?.type==="friend"&&Number(selected.data.id)===Number(u.id)?"selected":"";return `<button class="person messenger-person ${active}" data-kind="friend" data-id="${u.id}"><div class="person-avatar-wrap">${SocialNet.avatarHTML(u.avatar_url,u.name)}<i class="online-dot"></i></div><div class="person-text"><strong>${SocialNet.escape(u.name)}</strong><small>Ami · Conversation privée</small></div><span class="person-arrow">‹</span></button>`}
function groupHTML(g){const active=selected?.type==="group"&&Number(selected.data.id)===Number(g.id)?"selected":"";return `<button class="person messenger-person group-person ${active}" data-kind="group" data-id="${g.id}"><div class="person-avatar-wrap"><span class="group-avatar">👥</span></div><div class="person-text"><strong>${SocialNet.escape(g.name)}</strong><small>Groupe · ${Number(g.member_count||0)} membres</small></div><span class="person-arrow">‹</span></button>`}
function drawPeople(){const q=sl.value.trim().toLowerCase();let html="";if(activeTab!=="groups"){const list=people.filter(u=>u.name.toLowerCase().includes(q));if(list.length)html+=`<div class="chat-list-label">Amis</div>`+list.map(personHTML).join("");}if(activeTab!=="friends"){const list=groups.filter(g=>g.name.toLowerCase().includes(q));if(list.length)html+=`<div class="chat-list-label">Groupes</div>`+list.map(groupHTML).join("");}pl.innerHTML=html||'<div class="empty">لا توجد محادثات مطابقة.</div>'}
function renderHead(item){if(item.type==="group"){head.innerHTML=`<button class="mobile-back" id="mobileBack">→</button><div class="chat-user-head"><span class="group-avatar large">👥</span><div><strong>${SocialNet.escape(item.data.name)}</strong><small>Groupe · ${Number(item.data.member_count||0)} membres</small></div></div>`}else{const u=item.data;head.innerHTML=`<button class="mobile-back" id="mobileBack">→</button><div class="chat-user-head">${SocialNet.avatarHTML(u.avatar_url,u.name)}<div><strong>${SocialNet.escape(u.name)}</strong><small>Votre ami sur SocialNet</small></div></div>`}document.getElementById("mobileBack")?.addEventListener("click",()=>root?.classList.remove("show-chat"))}
function renderMessages(messages){const uid=Number(me()?.id);const key=messages.map(m=>m.id+":"+m.body+":"+m.created_at).join("|");if(key===lastRendered)return;lastRendered=key;if(!messages.length){ml.innerHTML='<div class="empty">Aucun message pour le moment.<br>Envoyez le premier message maintenant 👋</div>';return}ml.innerHTML=messages.map(m=>{const mine=Number(m.sender_id)===uid;let sender=mine?me():people.find(x=>Number(x.id)===Number(m.sender_id));const avatar=SocialNet.avatarHTML(sender?.avatar_url||m.sender_avatar,sender?.name||m.sender||"");return `<div class="message-row ${mine?"mine":"other"}">${avatar}<div class="bubble ${mine?"mine":"other"}"><div>${SocialNet.escape(m.body).replace(/\n/g,"<br>")}</div><small>${SocialNet.date(m.created_at)}${!mine&&selected?.type==="group"?` · ${SocialNet.escape(m.sender||sender?.name||"")}`:""}</small></div></div>`}).join("");ml.scrollTop=ml.scrollHeight}
async function loadChat(silent=false){if(!selected)return;try{const url=selected.type==="group"?`/api/groups/${selected.data.id}/messages`:`/api/messages/${selected.data.id}`;const d=await SocialNet.api(url);if(!silent)ml.innerHTML='<div class="loading">جاري تحميل Messages...</div>';renderMessages(d.messages||[])}catch(e){if(!silent)ml.innerHTML='<div class="empty">'+SocialNet.escape(e.message)+'</div>'}}
async function openChat(kind,id){const data=kind==="group"?groups.find(x=>Number(x.id)===Number(id)):people.find(x=>Number(x.id)===Number(id));if(!data)return;selected={type:kind,data};lastRendered="";drawPeople();renderHead(selected);form.classList.remove("hidden");root?.classList.add("show-chat");await loadChat(false);input.focus();clearInterval(pollTimer);pollTimer=setInterval(()=>loadChat(true),3000)}
pl.addEventListener("click",e=>{const b=e.target.closest("[data-kind]");if(b)openChat(b.dataset.kind,b.dataset.id)});
sl.addEventListener("input",drawPeople);
document.querySelectorAll(".chat-tab").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".chat-tab").forEach(x=>x.classList.remove("active"));btn.classList.add("active");activeTab=btn.dataset.tab;drawPeople()}));
form.addEventListener("submit",async e=>{e.preventDefault();const body=input.value.trim();if(!selected||!body)return;const btn=form.querySelector("button");btn.disabled=true;try{const url=selected.type==="group"?`/api/groups/${selected.data.id}/messages`:`/api/messages/${selected.data.id}`;await SocialNet.api(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({body})});input.value="";lastRendered="";await loadChat(false);input.focus()}catch(x){alert(x.message)}finally{btn.disabled=false}});
input.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();form.requestSubmit()}});
function renderGroupFriends(){groupFriends.innerHTML=people.map(u=>`<label class="group-friend"><input type="checkbox" name="member" value="${u.id}"><span>${SocialNet.avatarHTML(u.avatar_url,u.name)}</span><span><strong>${SocialNet.escape(u.name)}</strong><small>Ami</small></span></label>`).join("")||'<div class="empty">Vous n’avez pas encore d’amis.</div>'}
async function loadGroups(){const d=await SocialNet.api("/api/groups");groups=d.groups||[]}
async function openGroupModal(){groupError.textContent="";groupForm.reset();renderGroupFriends();modal.classList.remove("hidden");groupName.focus()}
function closeGroupModal(){modal.classList.add("hidden")}
openGroupBtn.addEventListener("click",openGroupModal);closeGroupBtn.addEventListener("click",closeGroupModal);modal.addEventListener("click",e=>{if(e.target===modal)closeGroupModal()});
groupForm.addEventListener("submit",async e=>{e.preventDefault();groupError.textContent="";const ids=[...groupForm.querySelectorAll('input[name="member"]:checked')].map(x=>Number(x.value));if(ids.length<2){groupError.textContent="Choisissez au moins deux amis.";return}const btn=groupForm.querySelector("button[type=submit]");btn.disabled=true;try{const d=await SocialNet.api("/api/groups",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:groupName.value.trim(),member_ids:ids})});await loadGroups();activeTab="groups";document.querySelectorAll(".chat-tab").forEach(x=>x.classList.toggle("active",x.dataset.tab==="groups"));drawPeople();closeGroupModal();await openChat("group",d.group.id)}catch(err){groupError.textContent=err.message}finally{btn.disabled=false}});
(async()=>{try{const [f,g]=await Promise.all([SocialNet.api("/api/friends"),SocialNet.api("/api/groups")]);people=f.friends||[];groups=g.groups||[];drawPeople();const params=new URLSearchParams(location.search),gid=Number(params.get("group")),uid=Number(params.get("user"));if(gid&&groups.some(x=>Number(x.id)===gid))openChat("group",gid);else if(uid&&people.some(x=>Number(x.id)===uid))openChat("friend",uid)}catch(e){pl.innerHTML='<div class="empty">'+SocialNet.escape(e.message)+'</div>'}})();
window.addEventListener("beforeunload",()=>clearInterval(pollTimer));
